var mongoose = require('mongoose');

// Wallet Model
var Wallet = mongoose.model('Wallet', {
  // user: {
  //   type: new ObjectId
  // }, // this maps to the autogenerated ID in the User collection
  address: {
    type: String,
    required: true,
    trim: true
  },
  private_key: {
    type: String,
    required: false
  },
  public_key: {
    type: String,
    required: false
  }
});

module.exports = {Wallet};
