var mongoose = require('mongoose');

// Wallet Model
var Wallet = mongoose.model('Wallet', {
  _developer: {
    required: true,
    type: mongoose.Schema.Types.ObjectId
  }, // this maps to the autogenerated ID in the User collection
  user_id: { // dev sets the user id
    type: String,
    required: true,
    trim: true
  },
  address: {
    type: String,
    required: true,
    trim: true
  },
  private_key: {
    type: String,
    required: false
  },
  public_key: {
    type: String,
    required: false
  }
});

module.exports = {Wallet};
